# Generated by Django 4.2.7 on 2025-10-24 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('meal_time', models.CharField(choices=[('noon', 'Noon'), ('dinner', 'Dinner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feast',
                'verbose_name_plural': 'Feasts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_meal_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('half_meal_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Meal Rate',
                'verbose_name_plural': 'Meal Rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='meal_count',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_type',
            field=models.CharField(choices=[('full', 'Full Meal'), ('half', 'Half Meal')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('meal_deduction', 'Meal Deduction'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestFeastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_mobile', models.CharField(max_length=15)),
                ('requested_by_name', models.CharField(max_length=100)),
                ('requested_by_mobile', models.CharField(max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.feast')),
            ],
            options={
                'verbose_name': 'Guest Feast Request',
                'verbose_name_plural': 'Guest Feast Requests',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
