# Generated by Django 4.2.7 on 2025-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_feast_mealrate_mealrecord_meal_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='taken_dinner',
            field=models.BooleanField(default=False),
        ),
    ]
