# Generated by Django 4.2.7 on 2025-10-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0004_mealrecord_taken_dinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecord',
            name='taken_dinner',
        ),
    ]
